### ISSUE TITLE
Invlid XML format

### ISSUE THREAD

**Issue by arivers** [zhaoyanswill/RAPSearch2#10]
The XML file output by Rapsearch2 version 2.20 has a small formatting error that causes problems on some xml parsers (Python's cElementTree parser but not lxml). 
The tag:
`<Parameters_log-expect evalue>1</Parameters_log-expect evalue>`
has a space between "log-expect" and "evalue". 
Removing the space resulted in valid xml.

**Comment by zhaoyanswill** [comment]
Hi arivers, please check the latest version. Thanks!
