### ISSUE TITLE
compilation fails due to typo in Makefile

### ISSUE THREAD

**Issue by ctberthiaume** [zhaoyanswill/RAPSearch2#2]
There's a simple typo in the Makefile for version 2.17 where the wrong INC and LIBS lines are commented out.  It looks like the lines relative to the developer's home directory were accidentally left uncommented instead of the lines relative to the Src directory.  After switching the commented lines compilation completes OK.  Here's what the beginning of the install script output looks like, up to the first error.

```
RAPSearch installer
rm -f *.o rapsearch prerapsearch
g++ -c -O3 -w  HashSearch.cpp -o HashSearch.o -I ~/include
HashSearch.cpp:21:41: error: boost/chrono/thread_clock.hpp: No such file or directory
```

**Comment by zhaoyanswill** [comment]
Thank you very much, Chris! I've updated the Makefile.
