### ISSUE TITLE
RAPSearch v2.12 cannot find database issue

### ISSUE THREAD

**Issue by MDSharma** [zhaoyanswill/RAPSearch2#4]
Hello,

I am writing to you because I have come across a small hurdle with using RAPSearch2 (v2.12) for paired-end reads. I have downloaded this version from http://omics.informatics.indiana.edu/mg/get.php?software=rapsearch2.12_pair_64bits.tar.gz and installed as “pair-rapsearch” without any issues. I have also downloaded the latest v2.18 (and installed it as “rapsearch”).

My single file queries using v2.12 and v2.18 work without fail:
………..

> rapsearch -q LM_4603_R1.fastq.fasta -d /opt/rapsearch2/nr_db -z 32 -o LM_4603.rap -b 50 -v 50 -a t 
> QueryFileName LM_4603_R1.fastq.fasta
> Queries are nucleotide sequences in fasta format
>  start 32  threads
> ………..

However, if I try to run the paired end v2.12 using the same nr_db as above (created using prerapsearch v2.18) then the commands fail with the following warning:

………..

> pair-rapsearch -c LM_4601_R1.fastq.fasta LM_4601_R2.fastq.fasta -d /opt/rapsearch2/nr_db -z 6 -o ./LM_4601.rap -b 50 -v 50
> QueryFileNames LM_4601_R1.fastq.fastaLM_4601_R2.fastq.fasta
>  Build Hash File for Query 1...
>  Queries are nucleotide sequences
>  Build Hash File for Query 2...
>  Queries are nucleotide sequences
>  Can not open the database file
>  Please check the file name
> 
> > > Main END
> > >  Time used: 6 min (0.1 hours)
> > > ………..

I have looked into the .cpp files and it seems that the program looks for nr_db.info and should only give this message if it can’t find the file in the same directory as the nr_db file. However, the file clearly exists and is readable – as shown by the use within the single-ended run.

Please can you suggest what is going on and how to fix this?

Best,
MD

**Comment by zhaoyanswill** [comment]
Hi,

It should be no problem because you use an absolute path. Are these two 
commands executed under the same account?

Could you try to use 'ln -s' to make links for db and db_info in the 
working directory and see what happen? Also could you try to use 
presearch of paired-end version to make an indexed nr database? Thanks!

Sincerely,
Y. Z.

**Comment by MDSharma** [comment]
Hi,

Yes, both commands were executed under the same account and all file permissions are valid as well.

I just tried to run the paired command against a database prepared using the paired prerapsearch and got the same issue:

Build Hash File for Query 1...
Queries are nucleotide sequences
Build Hash File for Query 2...
Queries are nucleotide sequences
Can not open the database file
Please check the file name

> > > Main END
> > > Time used: 6 min (0.1 hours)

Also tried this with the ln-s solution but to no avail. In both cases, the single fasta file gets processed without any drama.

Any chance you could help debug this?

Cheers,
MD

Dr. M D Sharma
Associate Research Fellow
Centre for Ecology & Conservation
College of Life and Environmental Sciences
University of Exeter
Cornwall Campus
Penryn
TR10 9EZ

M.D.Sharma@Exeter.ac.ukhttps://legacy.exeter.ac.uk/owa/redir.aspx?C=2550a33f6b904272a7b1147002360f76&URL=mailto%3aM.D.Sharma%40Exeter.ac.uk
http://www.publicationslist.org/MD.Sharmahttps://legacy.exeter.ac.uk/owa/redir.aspx?C=2550a33f6b904272a7b1147002360f76&URL=http%3a%2f%2fwww.publicationslist.org%2fMD.Sharma
http://www.researcherid.com/rid/F-8530-2013

Shared Tel: (+44)  1326 259384
Mob: (+44) 7919 242450
[http://www.exeter.ac.uk/codebox/email-sig/images/logo.gif]http://www.exeter.ac.uk/

[http://www.exeter.ac.uk/codebox/email-sig/images/fb.gif]http://www.facebook.com/exeteruni[http://www.exeter.ac.uk/codebox/email-sig/images/twitter.gif]http://twitter.com/uniofexeter[http://www.exeter.ac.uk/codebox/email-sig/images/youtube.gif]http://www.youtube.com/universityofexeter[http://www.exeter.ac.uk/codebox/email-sig/images/li.gif]http://www.linkedin.com/groups/University-Exeter-109267?mostPopular=&gid=109267

This email and any attachment may contain information that is confidential, privileged, or subject to copyright, and which may be exempt from disclosure under applicable legislation. It is intended for the addressee only. If you received this message in error, please let me know and delete the email and any attachments immediately. The University will not accept responsibility for the accuracy/completeness of this e-mail and its attachments.

**Comment by zhaoyanswill** [comment]
Hi,

I just did a test on the data in my hand. I indexed the database and 
then searched queries. RAPSearch2 worked without any problem.

Could you try to re-build RAPSearch2 and see what happen? Thanks!

Sincerely,
Yongan

**Comment by MDSharma** [comment]
Hi Yongan,

Turns out that rapsearch2 v 2.12 does not like the db file to be anywhere BUT in the local directory. Even links do not work. I moved the db into the same directory as the .fasta files and it’s running as a charm.

Do you happen to have any instructions / tutorials associated with importing RAPSearch2 data into MEGAN etc?

Best,
MD

Dr. M D Sharma
Associate Research Fellow
Centre for Ecology & Conservation
College of Life and Environmental Sciences
University of Exeter
Cornwall Campus
Penryn
TR10 9EZ

M.D.Sharma@Exeter.ac.ukhttps://legacy.exeter.ac.uk/owa/redir.aspx?C=2550a33f6b904272a7b1147002360f76&URL=mailto%3aM.D.Sharma%40Exeter.ac.uk
http://www.publicationslist.org/MD.Sharmahttps://legacy.exeter.ac.uk/owa/redir.aspx?C=2550a33f6b904272a7b1147002360f76&URL=http%3a%2f%2fwww.publicationslist.org%2fMD.Sharma
http://www.researcherid.com/rid/F-8530-2013

Shared Tel: (+44)  1326 259384
Mob: (+44) 7919 242450
[http://www.exeter.ac.uk/codebox/email-sig/images/logo.gif]http://www.exeter.ac.uk/

[http://www.exeter.ac.uk/codebox/email-sig/images/fb.gif]http://www.facebook.com/exeteruni[http://www.exeter.ac.uk/codebox/email-sig/images/twitter.gif]http://twitter.com/uniofexeter[http://www.exeter.ac.uk/codebox/email-sig/images/youtube.gif]http://www.youtube.com/universityofexeter[http://www.exeter.ac.uk/codebox/email-sig/images/li.gif]http://www.linkedin.com/groups/University-Exeter-109267?mostPopular=&gid=109267

This email and any attachment may contain information that is confidential, privileged, or subject to copyright, and which may be exempt from disclosure under applicable legislation. It is intended for the addressee only. If you received this message in error, please let me know and delete the email and any attachments immediately. The University will not accept responsibility for the accuracy/completeness of this e-mail and its attachments.

**Comment by zhaoyanswill** [comment]
Hi,

Happy to hear the problem is solved! I've not seen this before. I 
usually put all db file in a directory and run RAPSearch2 where fasta 
files are placed. Thanks!

Sincerely,
Y. Z.
